import java.awt.*;
import java.awt.event.*;


class CalculatorX
{
    public static void main(String A[])
    {
        Calculator cobj = new Calculator(300,375,"CalculatorX");
    }
}

class Calculator extends WindowAdapter implements ActionListener            //Both class and interface from java.awt.event.*
{
    public Frame mainframe;
    public Button b1,b2,b3,b4;
    public TextField t1,t2;
    public Label lobj;
    Integer No1, No2;

    public Calculator(int Width, int Height, String Title)
    {
        //Frame creation
        mainframe = new Frame(Title);                                       //Name on frame
        mainframe.setSize(Width,Height);                                    //Size of frame
        mainframe.setLocation(50,50);                                       //Location on scrren from X and Y axis 
        mainframe.addWindowListener(this);                                  


        //button creation
        b1 = new Button("ADD");                                             
        b1.setBounds(30,220,100,30);                                         //Location setting
        mainframe.add(b1);                                                  //Add in frame
        b1.addActionListener(this);                                         //Output


        b2 = new Button("SUB");
        b2.setBounds(170,220,100,30);
        mainframe.add(b2);
        b2.addActionListener(this);


        b3 = new Button("MULT");
        b3.setBounds(30,280,100,30);
        mainframe.add(b3);
        b3.addActionListener(this);


        b4 = new Button("DIV");
        b4.setBounds(170,280,100,30);
        mainframe.add(b4);
        b4.addActionListener(this);


        //textfield creation 
        t1 = new TextField();                                               
        t1.setBounds(30,75,100,40);                                        //Location setting
        mainframe.add(t1);                                                  //Add in frame


        t2 = new TextField();
        t2.setBounds(170,75,100,40);
        mainframe.add(t2);       
        

        //label creation    
        lobj = new Label("Result : ");                                                
        lobj.setBounds(100,120,200,100);                                    //Location setting(X,Y,W,H)
        mainframe.add(lobj);

      
        mainframe.setLayout(null);
        mainframe.setVisible(true);
    }

    //To close button work
    public void windowClosing(WindowEvent wobj)                              //windowClosing from WindowAdaptor class
    {
        System.exit(0);                                             
    }

    //logic for buttons
    public void actionPerformed(ActionEvent aobj)                           //gave event object as parameter
    {
        try
        {
            No1 = Integer.parseInt(t1.getText());                           //From texfield get input as sting (getText()) convert to integer(Integer.parseInt()) and store in No1
            No2 = Integer.parseInt(t2.getText());

            if(aobj.getSource() == b1)                                      //Clicked on button b1
            {
                lobj.setText("Addition is : "+(No1+No2));
            }
            else if(aobj.getSource() == b2)
            {
                lobj.setText("Substraction is : "+(No1-No2));
            }
            else if(aobj.getSource() == b3)
            {
                lobj.setText("Multiplication is : "+(No1*No2));
            }
            else if(aobj.getSource() == b4)
            {
                lobj.setText("Division is : "+(No1/No2));
            }
        }
           catch (NumberFormatException eobj) 
        {
            lobj.setText("Invalid input");
        }
        catch (ArithmeticException eobj) 
        {
            lobj.setText("Error: Division by zero.");
        }
        catch(Exception eobj)
        {}
    }
}



/*
WindowEvent are low level event that indicate that windowa has changed its status,
This low level event generated by a window object when it is opened, closed, activated, deactivated.

This event pass to WindowListener or WindowAdaptor (windowClosing()) when addWindowListener method is used.
*/